config/routes.rb
HackerNewsRails::Application.routes.draw do

  root :to => 'hackers#index'

  #resources :hackers

  # ... shortcut for ...

  get "/hackers", to: "hackers#index", as: :hackers
  post "/hackers", to: "hackers#create"
  get "/hackers/new", to: "hackers#new", as: :new_hacker
  get "/hackers/:id/edit", to: "hackers#edit", as: :edit_hacker
  get "/hackers/:id", to: "hackers#show", as: :hacker
  put "/hackers/:id", to: "hackers#update"
  #delete "/hackers/:id", to: "hackers#destroy"

  # ... shortcut for ...

  match "/hackers/:id", to: "hackers#destroy", via: [:delete]

  # ... custom routes are okay, too!

  match "/xxx", to: "hackers#index", as: :porno, via: [:get, :put, :delete]

  resources :bonobos do
    resources :eyes
    resource :tail
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :title, :body
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController

  def index
    @ken = User.new
    @users = User.all
    @comment = Comment.new
    @comments = Comment.all
  end

  def create
    @ken = User.new params[:user]
    if @ken.save
      redirect_to root_path
    else
      # do something
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hackers/index.html.erb
<p>This is the first paragraph of HackerNews</p>


<%= form_for @ken, url: hackers_path, html:{class: "user_form"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <%= f.label :email %>:
  <%= f.text_field :email %>
  <%= f.submit "Create Account" %>
<% end %>
</br>
</br>
<ul>
<p>Delete Users:</p>
<% @users.each do |user| %>
<li>
  <%= link_to hacker_path(user.id), method: :delete  do %>
  <h1><%= user.email %></h1>
  <p>Now is the time</p>
  <% end %>

</li>
<% end %>
</ul>

<h3><%= link_to "Get it on", porno_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNewsRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>New Hackernews Website</h1>
<%= yield %>



</body>
</html>